server:
  port: 8082

spring:
  activiti:
    check-process-definitions: false
    database-schema-update: true
  application:
    name: activiti-service
  datasource:
    url: jdbc:mysql://10.237.161.213:3306/gs_acti?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: user_dev
    password: Zaq_2wsx
  jpa:
    show-sql: true
    database: mysql
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
easy:
  upload-file:
    base-path: C:\workspace\easy-activiti\activiti-service\target\classes
  autoboxing:
    ignore:
      patterns:
        - /swagger-resources/**
        - /swagger-ui.html
        - /v2/api-docs
        - /webjars/**
        - /csrf
        - /
      heasers:
        - USING_FEIGN
  swagger:
    security:
      enabled: true
      schemes:
        Authorization:
          key-name: Authorization
        tenantId:
          key-name: tenantId
        USER_ID:
          key-name: USER_ID
